#!/usr/bin/env bash
#write a bash script that displays To infinity and beyond indefinitely
#with a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
#Make a copy of your 6 script, name it 67-stop_me_if_you_can, that kills the 7 process instead of the 4 one.
