#!/usr/bin/env bash
#This is a for loop
i=1
for i in {1..10}
do  
        echo "Best School"
	i=$i
done                                                                                                
