#!/usr/bin/env bash
#This is a for loop
i=1
while [ $i -le 10 ]
do  
        echo "Best School"
    
    i=$(( $i + 1 ))
done
~                                                                                                   
