#!/usr/bin/env bash
#This is a while loop with case statement
x=1
while [ $x -le 20 ]
case $x in
	4)echo -e $x="bad luck from China"
		x=$(( $x + 1 ));;
	9)echo -e 4$x="bad luck from Japan"
		x=$(( $x + 1 ));;
	17)echo -e $x="bad luck from Italy"
		x=$(( $x + 1 ));;
	*) x=$(( $x + 1 ))
echo
esac
done
